name: my_zama
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  adaptive_dialog: ^1.3.0
  algorand_dart: ^1.0.0
  bloc: ^8.0.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  font_awesome_flutter: ^9.2.0
  qr_flutter: ^4.0.0
  url_launcher: ^6.0.18
  walletconnect_dart: ^0.0.6
  walletconnect_secure_storage: ^1.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
